---
# tasks file for ServerSetup

  - name: "Install & update packages to last version"
    apt:
      pkg: "{{packages}}"
      state: present

  - name: add Docker gpg key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/trusted.gpg.d/docker.asc

  - name: add Docker repo
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present

  - name: Install & update packages to last version
    apt:
      update_cache: true
      pkg: "{{DockerNginxPkgs}}"
      state: present

  - name: Create group
    group:
      name: ansible
      state: present

  - name: Create ansible user(for deploy operations)
    user:
      name: ansible
      state: present
      password: "{{ PASSWD | password_hash('sha512','A512') }}"
      shell: /bin/bash
      generate_ssh_key: true
      group: ansible

  - name: Add users to docker group and enable services
    user:
      name: "{{item}}"
      groups: docker
      append: yes
    with_items: "{{docker_users}}"
    notify: Enable services

  - name: Create Project Folder
    file:
      path: /var/www/{{project_name}}
      state: directory
      recurse: yes
      owner: www-data
      group: www-data
      mode: 0755

